server:
  port: 8081
spring:
    datasource:
        name: exam_demo
        url: jdbc:mysql://127.0.0.1:3300/exam_demo?useUnicode=true&characterEncoding=UTF-8&useSSL=true
        username: root
        password: 2016626abc
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20   
        
mybatis:
  mapper-locations: 
     classpath: com/scau/common/mapper/*.xml
  type-aliases-package: com.scau.common.domain
#分页的配置
pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: true
  reasonable: true
#热部署配置
#热部署生效
spring.devtools.restart.enabled: true
---
spring:
   profiles: dev
   datasource:
        name: exam_demo
        url: jdbc:mysql://127.0.0.1:3300/exam_demo?useUnicode=true&characterEncoding=UTF-8&useSSL=true
        username: root
        password: 2016626abc
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20   
server.port: 8089
logging.config: 
     classpath:log4j2-dev.xml
---
spring:
   profiles: test
server.port: 8083
logging.config: 
     classpath:log4j2-test.xml
---
spring:
   profiles: prd
   datasource:
        name: exam_demo
        url: jdbc:mysql://db-tk.zyapi.com.cn:3306/exam?useUnicode=true&amp;characterEncoding=UTF-8&amp;allowMultiQueries=true
        username: exam_db
        password: Adminis2danger!
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20   
server.port: 8080
logging.config: 
     classpath:log4j2-prd.xml